CREATE TABLE APP_USER (
    ID uniqueidentifier PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
)